/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CountRouteImport } from './routes/count'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersAllRouteImport } from './routes/users/all'
import { Route as UsersUsernameRouteImport } from './routes/users/$username'
import { Route as PostsIdRouteImport } from './routes/posts.$id'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CountRoute = CountRouteImport.update({
  id: '/count',
  path: '/count',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersAllRoute = UsersAllRouteImport.update({
  id: '/users/all',
  path: '/users/all',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRoute = UsersUsernameRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/count': typeof CountRoute
  '/home': typeof HomeRoute
  '/posts/$id': typeof PostsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/users/all': typeof UsersAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/count': typeof CountRoute
  '/home': typeof HomeRoute
  '/posts/$id': typeof PostsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/users/all': typeof UsersAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/count': typeof CountRoute
  '/home': typeof HomeRoute
  '/posts/$id': typeof PostsIdRoute
  '/users/$username': typeof UsersUsernameRoute
  '/users/all': typeof UsersAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/count'
    | '/home'
    | '/posts/$id'
    | '/users/$username'
    | '/users/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/count'
    | '/home'
    | '/posts/$id'
    | '/users/$username'
    | '/users/all'
  id:
    | '__root__'
    | '/'
    | '/count'
    | '/home'
    | '/posts/$id'
    | '/users/$username'
    | '/users/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountRoute: typeof CountRoute
  HomeRoute: typeof HomeRoute
  PostsIdRoute: typeof PostsIdRoute
  UsersUsernameRoute: typeof UsersUsernameRoute
  UsersAllRoute: typeof UsersAllRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count': {
      id: '/count'
      path: '/count'
      fullPath: '/count'
      preLoaderRoute: typeof CountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/all': {
      id: '/users/all'
      path: '/users/all'
      fullPath: '/users/all'
      preLoaderRoute: typeof UsersAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username': {
      id: '/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof UsersUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountRoute: CountRoute,
  HomeRoute: HomeRoute,
  PostsIdRoute: PostsIdRoute,
  UsersUsernameRoute: UsersUsernameRoute,
  UsersAllRoute: UsersAllRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
